# File: .github/workflows/data-harvester.yml
name: Data Harvester

on:
  schedule:
    # Corporate feeds every 5 minutes → 08:00-20:00 BRT maps to 11:00-23:00 UTC
    - cron: '*/5 11-23 * * *'
    # Macro feeds every 15 minutes → 08:00-20:00 BRT maps to 11:00-23:00 UTC
    - cron: '*/15 11-23 * * *'
  workflow_dispatch: {}

jobs:
  harvest:
    name: Executar Coletores RSS
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Atualizar pip
        run: python -m pip install --upgrade pip

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Coletor Corporate (RSS)
        if: github.event_name == 'schedule' && contains(github.event.schedule, '*/5')
        run: python main.py --which corporate --once

      - name: Coletor Macro (RSS)
        if: github.event_name == 'schedule' && contains(github.event.schedule, '*/15')
        run: python main.py --which macro --once

      - name: Coletor Completo Manual
        if: github.event_name == 'workflow_dispatch'
        run: python main.py --which all --once
